export { default as logo1 } from "./origami.svg";
export { default as logo1_bg } from "./origami_bg.svg";
export { default as logo1_bird } from "./origami_bird.svg";
export { default as logo2 } from "./origami2.svg";
export { default as logo2_bg } from "./origami2_bg.svg";
export { default as logo2_bird } from "./origami2_bird.svg";
export { default as bunny } from "./bunnyTitle5.svg";
export { default as cz } from "./czflag.svg";
export { default as uk } from "./ukflag.svg";
