export const SKILLS = [
  { href: "#git_", title: "Git(Hub)", weight: 2 },
  { href: "#json_", title: "JSON", weight: 2 },
  { href: "#html_", title: "HTML", weight: 1 },
  { href: "#react_", title: "React", weight: 1 },
  { href: "#react_", title: "Next", weight: 2 },
  { href: "#python_", title: "Python", weight: 1 },
  { href: "#sql_", title: "MongoDB", weight: 2 },
  { href: "#npm_", title: "npm", weight: 2 },
  { href: "#jest_", title: "jest", weight: 2 },
  { href: "#css_", title: "CSS", weight: 1 },
  { href: "#jquery_", title: "jQuery", weight: 2 },
  { href: "#express_", title: "Express", weight: 2 },
  { href: "#js_", title: "JavaScript", weight: 1 },
  { href: "#java_", title: "Java", weight: 1 },
  { href: "#selenium_", title: "Selenium", weight: 2 },
  { href: "#node.js_", title: "Node.js", weight: 1 },
  { href: "#photoshop_", title: "Photoshop", weight: 2 },
  { href: "#oauth_", title: "OAuth", weight: 2 },
  { href: "#premier-pro_", title: "After Effects", weight: 2 },
];
